// <auto-generated />
namespace SelfLearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class student_subject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_subject));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141738339_student_subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
